GET http://localhost:3000/api/v1/product-request/
?limit=10
&page=1
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.uLUQKCAZ3c_a94nMsfDMCYLRNHdkET0xoLd-DVVj4Aw
lang: ar



GET http://localhost:3000/api/v1/product-request/67ecce7e2f1cf0a29baa8430
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWNjZTQ5MmYxY2YwYTI5YmFhODQyOSIsIm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQHVzZXJ4LmNvbSIsInJvbGUiOiJ1c2VyIiwiYWdlIjoyNywiZ2VuZGVyIjoibWFsZSIsImlhdCI6MTc0MzU4NDQ5MiwiZXhwIjoxNzQzNTg4MDkyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.dJrmhWpVUfwOfEvZKIS4DbBeIF04eyqC8a3ozJc7Cd8
lang: ar

