DELETE http://localhost:3000/api/v1/product-request/67eccdb786b5d051804c00f6
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWNjZDNlODZiNWQwNTE4MDRjMDBmMiIsIm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwicm9sZSI6InVzZXIiLCJhZ2UiOjI3LCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNzQzNTkyNjk0LCJleHAiOjE3NDM1OTYyOTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.GR1Trq-jnqi5GbqTd7C1MRViu0KctEnK0hlqnnTzU7Y
lang: ar


