GET http://localhost:3000/api/v1/product-request/
?limit=10
&page=1
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWNjZDNlODZiNWQwNTE4MDRjMDBmMiIsIm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwicm9sZSI6InVzZXIiLCJhZ2UiOjI3LCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNzQzNTkyNjk0LCJleHAiOjE3NDM1OTYyOTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.GR1Trq-jnqi5GbqTd7C1MRViu0KctEnK0hlqnnTzU7Y
lang: ar



GET http://localhost:3000/api/v1/product-request/67ecce7e2f1cf0a29baa8430
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWNjZTQ5MmYxY2YwYTI5YmFhODQyOSIsIm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQHVzZXJ4LmNvbSIsInJvbGUiOiJ1c2VyIiwiYWdlIjoyNywiZ2VuZGVyIjoibWFsZSIsImlhdCI6MTc0MzU4NDQ5MiwiZXhwIjoxNzQzNTg4MDkyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.dJrmhWpVUfwOfEvZKIS4DbBeIF04eyqC8a3ozJc7Cd8
lang: ar

