### Create Product
POST http://localhost:3000/api/v1/product
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.uLUQKCAZ3c_a94nMsfDMCYLRNHdkET0xoLd-DVVj4Aw

--boundary
Content-Disposition: form-data; name="name[en]"

Adidas Air Max
--boundary
Content-Disposition: form-data; name="name[ar]"

اديداس اير ماكس
--boundary
Content-Disposition: form-data; name="description[en]"

Comfortable and stylish shoes
--boundary
Content-Disposition: form-data; name="description[ar]"

أحذية مريحة وأنيقة
--boundary
Content-Disposition: form-data; name="price"

99.99
--boundary
Content-Disposition: form-data; name="quantity"

10
--boundary
Content-Disposition: form-data; name="category"

67e9b24566fb1fae1044e41d
--boundary
Content-Disposition: form-data; name="imageCover"; filename="test-image.jpeg"
Content-Type: image/jpeg

< ./test-image.jpeg
--boundary
Content-Disposition: form-data; name="images"; filename="test-image2.jpg"
Content-Type: image/jpeg

< ./test-image2.jpg
--boundary
Content-Disposition: form-data; name="images"; filename="test-image.jpeg"
Content-Type: image/jpeg

< ./test-image.jpeg
--boundary--
