GET http://localhost:3000/api/v1/users/
?limit=10
&page=1&sort=desc&search=doe
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJyb2xlIjoiYWRtaW4ifQ.mwRIj6zCmVo5Zo5Ey__BkEiOszfshZdsBUHRJZEexfQ


GET http://localhost:3000/api/v1/users/67ad8f4f2f0b5662151b1d70
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJyb2xlIjoiYWRtaW4ifQ.mwRIj6zCmVo5Zo5Ey__BkEiOszfshZdsBUHRJZEexfQ



GET http://localhost:3000/api/v1/user/profile
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGVhMzdjZmU1YmVhYjIyY2QyZjJlNyIsIm5hbWUiOiJyZXJlIiwiZW1haWwiOiJyZWVyQGR4ZHhzb2UuY29tIiwicm9sZSI6ImFkbWluIiwiYWdlIjo2NiwiYWN0aXZlIjp0cnVlLCJnZW5kZXIiOiJtYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wMy0yMlQxMTo0ODoxMi44NzlaIiwidXBkYXRlZEF0IjoiMjAyNS0wMy0yMlQxMTo0ODoxMi44NzlaIiwiX192IjowLCJpYXQiOjE3NDI2NTYxOTcsImV4cCI6MTc0MjY1OTc5NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.1QW41WbTPMEjqYbEJ37gl_Hdz305XNByt5bjMIY-JVo
