GET http://localhost:3000/api/v1/users/
?limit=10
&page=1&sort=desc&search=doe
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJyb2xlIjoiYWRtaW4ifQ.mwRIj6zCmVo5Zo5Ey__BkEiOszfshZdsBUHRJZEexfQ


GET http://localhost:3000/api/v1/users/67ad8f4f2f0b5662151b1d70
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJyb2xlIjoiYWRtaW4ifQ.mwRIj6zCmVo5Zo5Ey__BkEiOszfshZdsBUHRJZEexfQ



GET http://localhost:3000/api/v1/user/profile
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGVhMzdjZmU1YmVhYjIyY2QyZjJlNyIsIm5hbWUiOiJyZXJlIiwiZW1haWwiOiJyZWVyQGR4ZHhzb2UuY29tIiwicm9sZSI6InVzZXIiLCJhZ2UiOjY2LCJhY3RpdmUiOnRydWUsImdlbmRlciI6Im1hbGUiLCJjcmVhdGVkQXQiOiIyMDI1LTAzLTIyVDExOjQ4OjEyLjg3OVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTAzLTIyVDExOjQ4OjEyLjg3OVoiLCJfX3YiOjAsImlhdCI6MTc0MjY0NzI4OSwiZXhwIjoxNzQyNjUwODg5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.gyMOBzd5y_LdAOI9TTJodKzaXPALInhJR0UrnkYHpqM; 
